version: "3.9"
services:
  k8-rebuild-rest-api:
    build:
      context: ./k8-rebuild/k8-rebuild-rest-api
      dockerfile: Source/Service/Dockerfile
    ports:
      - 8888:80
    restart: unless-stopped
  k8-rebuild-file-drop:
    build: ./k8-rebuild/k8-rebuild-file-drop/app
    restart: unless-stopped
  reverse-proxy:
    image: nginx:alpine
    restart: unless-stopped
    environment:
      - NGINX_ENTRYPOINT_QUIET_LOGS=1
    ports:
      - 80:80
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
  file-handling:
    build:
      context: .
      dockerfile: Source/Service/Glasswall.EBS.Rebuild/Dockerfile
    environment:
      REBUILD_API_BASE_URL: "k8-rebuild-rest-api:8888?"
      CRONJOB_PERIOD: 15
      FORLDERS_PATH: /data/folder-to-folder
      DOTNET_ENVIRONMENT: Development
    restart: unless-stopped
    volumes:
      - /data/folder-to-folder:/data/folder-to-folder