version: "3.9"
services:
  k8-rebuild-rest-api:
    build:
      context: ./k8-rebuild/k8-rebuild-rest-api
      dockerfile: Source/Service/Dockerfile
    ports:
      - 8888:80
    restart: unless-stopped
  k8-rebuild-file-drop:
    build: ./k8-rebuild/k8-rebuild-file-drop/app
    restart: unless-stopped
  reverse-proxy:
    image: nginx:alpine
    restart: unless-stopped
    environment:
      - NGINX_ENTRYPOINT_QUIET_LOGS=1
    ports:
      - 80:80
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro